// Auto-generated by i18n-plugin. Do not edit.
export const locales = ['de', 'en', 'tr'] as const;
export const cookieName = 'LOCALE';
export const cookieMaxAge = 34560000;

let _storage: import('node:async_hooks').AsyncLocalStorage<{ locale: string }> | null | undefined =
	undefined;

export function getLocale(): string {
	if (_storage) {
		const s = _storage.getStore();
		if (s?.locale) return s.locale;
	}
	if (typeof document !== 'undefined') {
		const l = document.documentElement.lang;
		if (l) return l;
	}
	return 'de';
}

export function getLocales() {
	return locales;
}

export function setLocale(locale: string): void {
	if (typeof document !== 'undefined' && (locales as readonly string[]).includes(locale))
		document.documentElement.lang = locale;
}

export function getTextDirection(locale: string): string {
	return ['ar', 'he', 'fa', 'ur'].includes(locale) ? 'rtl' : 'ltr';
}

export function deLocalizeUrl(url: URL | string): URL {
	return typeof url === 'string' ? new URL(url) : url;
}

export async function runWithLocale<T>(locale: string, fn: () => T | Promise<T>): Promise<T> {
	if (_storage === undefined) {
		try {
			const { AsyncLocalStorage } = await import(/* @vite-ignore */ 'node:async_hooks');
			_storage = new AsyncLocalStorage();
		} catch {
			_storage = null;
		}
	}
	if (_storage) return _storage.run({ locale }, fn) as Promise<T>;
	return fn() as Promise<T>;
}

const _li: Record<string, number> = { de: 0, en: 1, tr: 2 };

function _t(tr: string[], p?: Record<string, string | number>): string {
	const text = tr[_li[getLocale()] ?? 0] ?? tr[0] ?? '';
	if (!p) return text;
	return text.replace(/\{(\w+)}/g, (_, k) => String(p[k] ?? '{' + k + '}'));
}
